### PR TITLE
display joiners' IP on join

### PR DESCRIPTION
**Pull request by zerfgog**
:^)
untested because dEV ON PRODUCTION

### CODE REVIEW

**Comment by SwadicalRag** [comment]
:+1: @meepdarknessmeep pls

**Comment by Velkon** [comment]
:+1:

**Comment by mcd1992** [comment]
Save to a DB and load/create on join.

**Comment by meepdarknessmeep** [comment]
it's using a seed, you don't have to

**Comment by zerfgog** [comment]
why when we can use a seeded- fuckin' ninjas

**Comment by mcd1992** [comment]
:+1:

**Comment by mcd1992** [comment]
Zarf change the seed var name since it's a shit name for a 'global' var and I'll test it sometime.

**Comment by meepdarknessmeep** [comment]
```
randomIntSeed = steamID & (2^32 - 1);
```

this is Wrong

**Comment by meepdarknessmeep** [comment]
fix it zard

**Pull request merged**
