### PR TITLE
Buncha fixes

### PR DESCRIPTION
**Pull request by meepdarknessmeep**
fixes #169 
fixes setmetatable({},{__tostring=error}) bug causing infinite loop and crashing program
fixes timer.* and http.* callbacks being allowed to cause infinite loops
rewrites the lua plugin to use better classes

### CODE REVIEW

**Comment by SwadicalRag** [comment]
if u put sports grade suspension, monster truck wheels, and a v16 engine on a go kart, its still a go kart

Ok

**Comment by zerfgog** [comment]
@SwadicalRag what if you change out the body? If all parts of the hammer are replaced, is it still a hammer?

**Comment by SwadicalRag** [comment]
yes

**Comment by SwadicalRag** [comment]
Ok

**Pull request merged**
