### PR TITLE
Update imagereply.lua

### PR DESCRIPTION
**Pull request by zeaga**
because SwadicalRag's a skid

### CODE REVIEW

**Comment by SwadicalRag** [comment]
:100:+
in memory of jon lau pls add

**Comment by willox** [comment]
jpeg pls

**Comment by mcd1992** [comment]
I declare @willox in charge of testing it. I'm just gonna hit merge and laugh.

**Comment by SwadicalRag** [comment]
haha who's laughing now

it's you mcd
you're laughing now
haha :clap: :laughing: :ok_hand:

**Comment by mcd1992** [comment]
topkek :ok_hand:

**Pull request merged**
