### PR TITLE
print join message for all joiners

### PR DESCRIPTION
**Pull request by zerfgog**

### CODE REVIEW

**Comment by SwadicalRag** [comment]
:+1: :ghost: people with IP!11

**Comment by zerfgog** [comment]
@mcd1992 this doesn't duplicate the message

**Comment by mcd1992** [comment]
Steam itself prints 'User connected' doesn't it?

**Comment by zerfgog** [comment]
yes it does, i thought you were talking about hash.
I doubt players will take much note, really

**Comment by mcd1992** [comment]
triggered

**Comment by meepdarknessmeep** [comment]
:cake: :fish_cake: :fish: :fishing_pole_and_fish:

**Comment by Velkon** [comment]
:-1:

**Comment by SwadicalRag** [comment]
pls i dont care i just want to scare people with fake ips!!

**Comment by mcd1992** [comment]
:-1:

**Pull request closed without merging**
